"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var vector_1 = require("./vector");
var v1 = new vector_1.Vector(6, 10);
var vector = new vector_1.Vector(6, 10);
console.log(vector.print());
console.log(vector.add(v1));
// console.log(vector.subs(v1));
// console.log(vector.mult(v1));
// console.log(vector.multNumber(3));
