import { Mobile } from "./mobile.js";
import { MobileCollection } from "./mobileCollection.js";
let mobile1 = new Mobile("celular", "Huawei", "p10", "black", 1300);
let mobile2 = new Mobile("Iphone", "Apple", "10", "Black", 1234);
let mobile3 = new Mobile("Kia", "Nokia", "3310", "blue", 300);
let mobile4 = new Mobile("ie", "Apple", "10", "green", 1800);
let myMobiles = [mobile1, mobile2, mobile3, mobile4];
let myCollection = new MobileCollection(myMobiles);
console.log(myCollection.printCollection());
console.log(myCollection.getTotalPrice());
